[versions]
forkhandles-bom = "2.25.1.0"
http4k-bom = "6.27.0.0"
intellij-platform = "2.11.0"
kotlin = "2.3.0"
swingx = "1.6.1"
version-catalog-update = "1.0.1"
versions = "0.53.0"

[libraries]
forkhandles-bom = { module = "dev.forkhandles:forkhandles-bom", version.ref = "forkhandles-bom" }
forkhandles-result4k = { module = "dev.forkhandles:result4k" }
forkhandles-values4k = { module = "dev.forkhandles:values4k" }
http4k-bom = { module = "org.http4k:http4k-bom", version.ref = "http4k-bom" }
http4k-cloudnative = { module = "org.http4k:http4k-cloudnative" }
http4k-format-jackson = { module = "org.http4k:http4k-format-jackson" }
http4k-format-jackson-yaml = { module = "org.http4k:http4k-format-jackson-yaml" }
http4k-multipart = { module = "org.http4k:http4k-multipart" }
swingx = { module = "org.swinglabs:swingx", version.ref = "swingx" }

[plugins]
intellij-platform = { id = "org.jetbrains.intellij.platform", version.ref = "intellij-platform" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "version-catalog-update" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }
